### ISSUE TITLE
nextpage/prevpage actions disabled when run via GBC

### ISSUE THREAD

**Issue by susobhsugathan** [FourjsGenero/fgl_table_actionpanel#5]
The actions prevpage and nextpage are disabled when run via GBC.
Using GDC, both actions are enabled and works as expected.
![123](https://user-images.githubusercontent.com/19838087/111124672-c44e8180-8596-11eb-8372-ece082da4ed5.png)

**Comment by fourjs-reuben** [comment]
Susobh, 
I have raised this previously with our dev team.  Deep down it is because the prevpage, nextpage actions are not listed https://4js.com/online_documentation/fjs-fgl-manual-html/#fgl-topics/c_fgl_prog_dialogs_predact_list.html, but are listed https://4js.com/online_documentation/fjs-fgl-manual-html/#fgl-topics/c_fgl_prog_dialogs_predact_list_local_actions.html and so the product is performing "as expected". 

Interesting thing is that something may happen with the other entries on the local action list, editcopy/editcut/editpaste there is work on the gbc clipboard, nextfield/prevfield is needed if you write your own virtual keyboard, nexttab/prevtab may be needed if we implement you can swipe through folder pages.

So I have not ruled out hope on this changing in the future.

For now I would suggest either hiding the prevpage / nextpage buttons, the user can always use the scrollbar, or tie them to your own actions that navigate backwards and forwards a page of rows. (where you look at AUI tree and use the bufferSize/pageSize attribute value as the number of rows to move)

Reuben

**Comment by susobhsugathan** [comment]
Hi Reuben,

Thanks for the reply.
Yes, for my application, i have written the NextPage/PrevPage by hand by making use of pageSize Attribute of the TABLE.

Susobh Sugathan
